[project]
name = "tool-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.2.7",
    "mcp>=1.9.4",
    "azure-ai-agents>=1.1.0b1",
    "semantic-kernel>=1.33.0",
]
