[project]
name = "python_and_java_multiagent"
version = "0.1.0"
description = "Create content using a multi-agent system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.0",
    "geopy>=2.4.1",
    "google-adk>=1.0.0",
    "gradio>=5.30.0",
    "a2a-sdk>=0.3.3"
]

